image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm run build && npm run build compiler

vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.1.0:vk6avJmuBqlMwZEelzdnZQ==
    - ms-vscode.csharp@1.21.4:lLV3lBwYKRTJ3QAQjtNMaQ==
